<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RollForward>Major</RollForward>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Common\Bookstore.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.CDK.Lib" Version="2.271.0" />
    <PackageReference Include="Cdklabs.CdkNag" Version="3.0.2" />
    <PackageReference Include="Constructs" Version="10.8.1" />
    <PackageReference Include="Amazon.Jsii.Analyzers" Version="1.140.0" PrivateAssets="all" />
  </ItemGroup>
</Project>